spring:
  application: 
    name: pdmp
   
  jpa: 
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
      
  datasource:
        url: jdbc:mysql://localhost:3306/pdmp
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: root
   
  logging:
    level:
        root: INFO
        org.springframework.security: INFO 
 
